####
#  Travis-CI configuration file for FreeCAD.
##
env:
  global:
   - FREECAD_RELEASE="0.16"
   - OSX_PORTS_CACHE="FreeCAD/FreeCAD-ports-cache"
   - CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:-Release}

os:
   - linux
   - osx

git:
  depth: 800

language: cpp

before_install:
- eval "$(curl -fsSL "https://raw.githubusercontent.com/${OSX_PORTS_CACHE}/v${FREECAD_RELEASE}/travis-helpers.sh")"
- |
  case "${TRAVIS_OS_NAME}" in

   "linux")
       sudo apt-get update -qq
       sudo apt-get install -y doxygen                        \
                               libboost-dev                   \
                               libboost-filesystem-dev        \
                               libboost-program-options-dev   \
                               libboost-python-dev            \
                               libboost-regex-dev             \
                               libboost-signals-dev           \
                               libboost-system-dev            \
                               libboost-thread-dev            \
                               libcoin60                      \
                               libcoin60-dev                  \
                               libeigen3-dev                  \
                               liboce-foundation-dev          \
                               liboce-foundation1             \
                               liboce-modeling-dev            \
                               liboce-modeling1               \
                               liboce-ocaf-dev                \
                               liboce-ocaf-lite-dev           \
                               liboce-ocaf-lite1              \
                               liboce-ocaf1                   \
                               liboce-visualization-dev       \
                               liboce-visualization1          \
                               libopencascade-modeling-6.5.0  \
                               libpyside-dev                  \
                               libqtcore4                     \
                               libshiboken-dev                \
                               libxerces-c-dev                \
                               libxmu-dev                     \
                               libxmu-headers                 \
                               libxmu6                        \
                               libxmuu-dev                    \
                               libxmuu1                       \
                               oce-draw                       \
                               pyside-tools                   \
                               python-dev                     \
                               python-pyside                  \
                               python-matplotlib              \
                               qt4-dev-tools                  \
                               qt4-qmake                      \
                               shiboken                       \
                               swig

       #Patch the system - there is a bug related to invalid location of libs on ubuntu 12.04
       sudo ln -s /usr/lib/x86_64-linux-gnu/ /usr/lib/i386-linux-gnu
       export DISPLAY=:99.0
       sh -e /etc/init.d/xvfb start

       CMAKE_ARGS=""
       INSTALLED_APP_PATH="/usr/local/bin/FreeCAD"
       ;;

   "osx")
       brew update >/dev/null && brew install jq
       if [ "${OSX_PORTS_CACHE}X" != "X" ]; then
            cacheContext=$(create_helper_context repo=${OSX_PORTS_CACHE} auth_token=${GH_TOKEN} release=${FREECAD_RELEASE})
            prime_local_ports_cache $cacheContext ${FREECAD_RELEASE}
       fi
       brew install eigen                       \
                    freetype                    \
                    qt                          \
                    python                      \
                    boost-python                \
                    pyside                      \
                    pyside-tools                \
                    xerces-c                    \
                    orocos-kdl                  \
                    homebrew/science/oce        \
                    homebrew/python/matplotlib
       brew install --with-oce homebrew/science/nglib
       brew install --without-framework --without-soqt sanelson/freecad/coin
       brew install --HEAD pivy

       #Install the 3DConnexion frameworks
       curl -o /tmp/3dFW.dmg -L 'http://www.3dconnexion.com/index.php?eID=sdl&ext=tx_iccsoftware&oid=a273bdbc-c289-e10d-816b-567043331c9e&filename=3DxWareMac_v10-2-5_r2142.dmg' && hdiutil attach -readonly /tmp/3dFW.dmg
       sudo installer -package /Volumes/3Dconnexion\ Software/Install\ 3Dconnexion\ software.pkg -target /

       #Remove GDAL if installed because it results in non-existent dependent library exceptions
       if [ -e /usr/local/lib/libgdal.1.dylib ]; then brew unlink gdal; fi

       CMAKE_ARGS="-DFREECAD_USE_EXTERNAL_KDL=ON -DBUILD_FEM_NETGEN=ON -DFREECAD_CREATE_MAC_APP=ON"
       INSTALLED_APP_PATH="/usr/local/FreeCAD.app/Contents/bin/FreeCAD"
       ;;

   *)
       echo "Invalid or unsupported operating system ${TRAVIS_OS_NAME}"
       exit 1
       ;;
  esac

install:
  - mkdir build && cd build && cmake ${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ../

script:
  - sudo make -j2 install
  - ${INSTALLED_APP_PATH} --run-test 0
  - ${INSTALLED_APP_PATH} --log-file /tmp/FreeCAD_installed.log &
  - sleep 10 && pkill FreeCAD
  - cat /tmp/FreeCAD_installed.log
  - grep --file=../.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "Error from .log_errors found!" && false )

after_success:
- |
  if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
     export VSN=$(python ${TRAVIS_BUILD_DIR}/src/Tools/ArchiveNameFromVersionHeader.py ${TRAVIS_BUILD_DIR}/build/src/Build/Version.h --git-SHA=$(git ls-remote origin master))
     export DEPLOYMENT_ARCHIVE=${VSN}.dmg
     appdmg ${TRAVIS_BUILD_DIR}/src/MacAppBundle/DiskImage/layout.json "${DEPLOYMENT_ARCHIVE}"
     deployContext=$(create_helper_context repo=${TRAVIS_REPO_SLUG} auth_token=${GH_TOKEN} release=${FREECAD_RELEASE})
     gitHub_deploy_asset_to_release_named $deployContext ${DEPLOYMENT_ARCHIVE}
     gitHub_prune_assets_for_release_named $deployContext "-OSX-" 3
  fi
